name: openai-gemini-api-key-rotator
services:
  openai-gemini-api-key-rotator:
    container_name: openai-gemini-api-key-rotator
    image: rpfilomeno/openai-gemini-api-key-rotator
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "12345:8990"
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
      - TZ=Asia/Manila
    # volumes:
    #   - D:\Github\openai-gemini-api-key-rotator\app:/app
    #entrypoint: /bin/sh /app/docker-entrypoint.sh
    networks:
      - local-services
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

# secrets:
#   discord:
#     file: ./discord.secret

networks:
  local-services:
    # Specify driver options
    driver: bridge
    external: true

volumes:
  D:
    external: true
    name: D
